### ISSUE TITLE
Error: write after end - onFinish @/morgan/index.js:130:14

### ISSUE THREAD

**Issue by furqanaziz** [expressjs/morgan#143]
```
Error: write after end
    at writeAfterEnd (_stream_writable.js:191:12)
    at RotatingFileStream.Writable.write (_stream_writable.js:238:5)
    at Array.logRequest (/home/info/HomePageCMS/node_modules/morgan/index.js:130:14)
    at listener (/home/info/HomePageCMS/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/info/HomePageCMS/node_modules/on-finished/index.js:100:5)
    at callback (/home/info/HomePageCMS/node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (/home/info/HomePageCMS/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:91:20)
    at ServerResponse.emit (events.js:188:7)
    at onFinish (_http_outgoing.js:592:10)
    at afterWrite (_stream_writable.js:383:3)
    at onwrite (_stream_writable.js:374:7)
    at WriteWrap.afterWrite [as oncomplete] (net.js:826:12)

**Comment by furqanaziz** [comment]
It is already been handled at https://github.com/expressjs/morgan/pull/73/files but I cannot see it is reflecting in latest commit.

**Comment by dougwilson** [comment]
Hi @furqanaziz the error you posted is that Morgan tried to log a request to the steam you provided, but your stream has ended, that is the "write after finish" is that Morgan wrote to your RotatingFileStream stream after that stream has ended. Unless you have a proposal (PRs welcome!) on what Morgan is supposed to do if the steam it was set to write to stopped accepting writes, that is an actual error condition, so the logging is validly logging that an error occurred.

**Comment by furqanaziz** [comment]
Seems like issue in plugin I was using. I changed to https://github.com/holidayextras/file-stream-rotator and error disappeared.

**Comment by dougwilson** [comment]
Weird enough, we used to suggest `file-stream-rotator` in the README until https://github.com/expressjs/morgan/pull/122 in which it was pointed to be unmaintained. If the replacement example doesn't even work, that's not good, either :(

**Comment by dougwilson** [comment]
The https://github.com/iccicci/rotating-file-stream module looks like it's maintained actively now (last publish 4 days ago). If you're still having this bug, please file an issue there so the module can fix it 👍
