### ISSUE TITLE
:total-time[digits] does not work

### ISSUE THREAD

**Issue by andrewtyl** [expressjs/morgan#240]
Trying to invoke the "total-time" logging option causes an error.

Code example below
`app.use(morgan(":total-time[3]");`

When a log is attempted, the express app crashes and the following error message appears. (edited pathnames for privacy).
```
undefined:7
    (tokens["total-time"](req, res, "3") || "-") + ""
                         ^

TypeError: tokens.total-time is not a function
    at eval (eval at compile (/.../node_modules/morgan/index.js:391:10), <anonymous>:7:26)
    at Array.logRequest (/.../node_modules/morgan/index.js:122:18)
    at listener (/.../node_modules/on-finished/index.js:169:15)
    at onFinish (/.../node_modules/on-finished/index.js:100:5)
    at callback (/.../node_modules/ee-first/index.js:55:10)
    at ServerResponse.onevent (/.../node_modules/ee-first/index.js:93:5)
    at ServerResponse.emit (events.js:203:15)
    at onFinish (_http_outgoing.js:671:10)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

Is this method depreciated? Documentation on npm shows this is should be a valid use.
https://www.npmjs.com/package/morgan#tokens

**Comment by ryhinchey** [comment]
this works for me.  could you add a reproducible example?

```js
var express = require('express')
var morgan = require('morgan')

var app = express()

app.use(morgan(':total-time[3]'))

app.listen(3001)
```

**Comment by andrewtyl** [comment]
Ah. I was on an older version. My b.
