### ISSUE TITLE
Heroku: Cannot find module 'debug'

### ISSUE THREAD

**Issue by simonh1000** [expressjs/morgan#55]
I'm struggling to deploy my server to Heroku. Below you see the result of running node from the Heroku CLI, and trying to `require` morgan. I'm getting the same issue in my logs and it is preventing the app from unless I comment out morgan.
```
> var morgan     = require("morgan");
Error: Cannot find module 'debug'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/app/node_modules/morgan/index.js:16:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```
Line 16 of index.js reads `var debug = require('debug')('morgan')`

Weirdly, everything runs fine on my development machine at home

**Comment by dougwilson** [comment]
Hi @simonh1000 , I'm sorry this issue slipped through the cracks for so long. I deploy to Heroku all the time and have never experienced this issue. Have you since resolve your issue? If not, you may want to try clearing the npm node_modules caching temporarily (https://github.com/heroku/heroku-buildpack-nodejs#enable-or-disable-node_modules-caching) and re-pushing. It may be caching a corrupted install of `morgan`.

**Comment by simonh1000** [comment]
This seemed to help, so thanks! :+1: -)

**Comment by dougwilson** [comment]
yay! :dancer:
